os: Visual Studio 2019

install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%

before_build:
  - nuget restore

build:
  project: Famoser.FexCompiler.sln
  verbosity: minimal

test_script: 
    - .\packages\OpenCover.4.7.922\tools\OpenCover.Console.exe -register:user -target:vstest.console.exe -targetargs:"Famoser.FexCompiler.Test.dll /logger:Appveyor /tests:UnitTests /Parallel /InIsolation" -targetdir:"Famoser.FexCompiler.Test\bin\Debug" -mergebyhash -skipautoprops -output:coverage.xml -filter:"+[Famoser.FexCompiler]* +[Famoser.FexCompiler]Famoser.FexCompiler.Properties.* -[Tests*]* -excludebyattribute:*.ExcludeFromCodeCoverage*" -hideskipped:All -returntargetcode
    - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
    - pip install codecov
    - codecov -f "coverage.xml"  

# preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
cache:
  - packages -> **\packages.config
