image: Visual Studio 2015

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: Famoser.FexCompiler.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\Famoser.FexCompiler.Test\bin\Debug\Famoser.FexCompiler.Test.dll -noshadow" -filter:"+[Famoser.FexCompiler*]* -[Famoser.FexCompiler.Test*]*" -output:".\MyProject_coverage.xml"
- codecov -f "MyProject_coverage.xml"
